### ISSUE TITLE
Does not work on Windows 10

### ISSUE THREAD

**Issue by Code4SAFrankie** [stockbsd/twitter-media-dl#7]
Gives me this error on Windows 10:```

Traceback (most recent call last):
  File "C:\WPy64-31040\python-3.10.4.amd64\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\WPy64-31040\python-3.10.4.amd64\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\WPy64-31040\python-3.10.4.amd64\Scripts\twitter-dl.exe\__main__.py", line 7, in <module>
  File "C:\WPy64-31040\python-3.10.4.amd64\lib\site-packages\twitter_dl\__main__.py", line 84, in main
    with open(args.confidential) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\User/.twitter.json'
```

**Comment by IntelligenXia** [comment]
Are we to provide the username/password or any other credentials here ?

**Comment by feelixs** [comment]
you need to sign up for a developer account on twitter, create a project and create .twitter.json in your user dir with contents:

`{"consumer_key": "apikey", "consumer_secret": "apisecret", "bearer_token": "bearer"}`
