### ISSUE TITLE
error 403

### ISSUE THREAD

**Issue by feelixs** [stockbsd/twitter-media-dl#8]
When I run the command
>twitter-dl 1609978596256354304 test.mp4 --tweet

I get the error
`ERROR   downloader: https://api.twitter.com/1.1/statuses/show.json error, code was 403
Traceback (most recent call last):
  File "C:\Users\mmh\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\mmh\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\mmh\AppData\Local\Programs\Python\Python310\Scripts\twitter-dl.exe\__main__.py", line 7, in <module>
  File "C:\Users\mmh\AppData\Local\Programs\Python\Python310\lib\site-packages\twitter_dl\__main__.py", line 98, in main
    downloader.download_media_of_tweet(args.resource_id, args.dest, args.size, args.video,
  File "C:\Users\mmh\AppData\Local\Programs\Python\Python310\lib\site-packages\twitter_dl\downloader.py", line 63, in download_media_of_tweet
    self.process_tweet(tweet, save_dest, size, include_video, include_photo)
  File "C:\Users\mmh\AppData\Local\Programs\Python\Python310\lib\site-packages\twitter_dl\downloader.py", line 193, in process_tweet
    if 'retweeted_status' in tweet:
TypeError: argument of type 'NoneType' is not iterable`

I've already added my key, secret, and bearer into my .twitter.json file, is there any way to avoid this 403 error?

**Comment by tahinETH** [comment]
same

**Comment by merajhasan88** [comment]
Not working for me either. On a Ubuntu 22.04. Created a project on Twitter, added the data to .twitter.json. Are we doing something wrong in enabling permissions in Twitter Developer Portal?
